### ISSUE TITLE
Do they still have a rate limit system ?

### ISSUE THREAD

**Issue by SS-Einsatzgruppe** [Lzyen/Fortnite-Codes-Generator#1]
thank you for the checker ! just cursors one i used a few moths ago had rate limit :/

**Comment by Lzyen** [comment]
I was not testing with the Epicgames Servers And Requests but i think no.

**Comment by Lzyen** [comment]
If you find epicgames has a rate limit maybe i can do a proxy system.

**Comment by SS-Einsatzgruppe** [comment]
Bruh !! Your too fast i just posted it <3
Truly thank for  the message back wasn't expecting that so fast !

im very new into python so i couldn't try and figure out how to add proxy support :-1:  to script i built so i just stuck it away i only know simple basic stuff sadly

**Comment by Lzyen** [comment]
No problem bro, I don't have social life, Lmao.

Yeah no problem if i found it has a rate limit i'm going to modify the code and add Proxy Support

**Comment by SS-Einsatzgruppe** [comment]
Love src code makes it easy for *unsmart people like me* to understand ! and i love how it sends ALl Generated Codes into a text file !! <3

i already got a handful of other people using it and they feel the same way about it ! cant wait to see what comes next !!

**Comment by Lzyen** [comment]
THANKS BRO YOU INSPIRE ME SO MUCH <3

**Comment by SS-Einsatzgruppe** [comment]
MAH FIRST WORKING CODE EVER !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1

**Comment by Lzyen** [comment]
YOH THEY WORK OMG GG, WHAT THE CODE GIVE YOU

**Comment by SS-Einsatzgruppe** [comment]
Broo sooo sorry had no idea that you responded ! i feel soo bad :-1: 

1K Vbucks and coode it found actually worked 100% i was scared it was a false postive but it wasnt

**Comment by SS-Einsatzgruppe** [comment]
Damn i feel so bad man ! \\\can we still be friends :( ????

**Comment by Lzyen** [comment]
Yeah Bro No Problem, Pls add me in discord, Junai#0001

**Comment by AlexandrM133** [comment]
здравствуйте, не могли бы вы мне объяснить как это работает, какие действия и в какой проследовательности мне надо делать что-бы запустить программу? зарание благодарю!
