### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by AlexandrM133** [Lzyen/Fortnite-Codes-Generator#2]
hello, could you explain to me how it works, what actions and in what sequence I need to do to run the program? Thank you in advance!

**Comment by SS-Einsatzgruppe** [comment]
Sir Look on FRont page it gives all info youll need to get program eunning # clone the repo

$ git clone https://github.com/Lzyen/Fortnite-Codes-Generator

# change the working directory to Fortnite Codes Generator
$ cd Fortnite-Codes-Generator

# install the requirements
$ python3 -m pip install -r requirements.txt
